services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: gamestack
        ports:
            - "8000:80"
        environment:
            APP_ENV: ${APP_ENV}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_COLLATION: ${DB_COLLATION}
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        command: >
            sh -c "
            ./wait-for-db.sh &&
            php artisan migrate &&
            apache2-foreground
            "

volumes:
    db_data:
