services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: gamestack_test
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        env_file:
            - .env.production
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        command: >
            sh -c "
            ./wait-for-db.sh &&
            php artisan migrate &&
            apache2-foreground
            "

volumes:
    db_data:
