name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: gamestack_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql
          ini-values: |
            memory_limit=512M
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set up environment variables
        run: |
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=${{secrets.APP_KEY}}" >> .env
          echo "DB_CONNECTION=${{secrets.DB_CONNECTION}}" >> .env
          echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
          echo "DB_DATABASE=${{secrets.DB_DATABASE}}" >> .env
          echo "DB_USERNAME=${{secrets.DB_USERNAME}}" >> .env
          echo "DB_PASSWORD=" >> .env
          echo "DB_COLLATION=utf8mb4_unicode_ci" >> .env

      - name: Display environment variables
        run: cat .env

      - name: Generate application key
        run: php artisan key:generate --env=production

      - name: Run migrations
        run: php artisan migrate --env=production --force

      - name: Run tests
        run: ./vendor/bin/pest

      - name: Update DB_HOST for production
        run: sed -i 's/DB_HOST=.*/DB_HOST=db/' .env

      - name: Update DB_PASSWORD for production
        run: sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=\${{secrets.DB_PASSWORD}}/' .env

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "yanisourir" --password-stdin

      - name: Build Docker image
        run: docker build -t yanisourir/gamestack:latest .

      - name: Docker push in registry
        run: docker push yanisourir/gamestack:latest

      - name: Deploy to RunCloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd webapps/gamestack-backend
            rm docker-compose.yml
            echo "${{ secrets.DOCKER_COMPOSE_FILE }}" >> docker-compose.yml
#             créer le docker compose yaml dans la webapps
#            docker pull yanisourir/gamestack:latest
#            docker-compose down
#            docker-compose up -d

